name: zentry
description: Portail mobile pour les agents avec gestion de projets et points d'entrée.



version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  geolocator: ^12.0.0
  crypto: ^3.0.3
  image: ^4.1.7
  google_maps_flutter: ^2.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: any
  hive_generator: any

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: true
  fullscreen: true


